
version: '3'
services:


  db:
    image: postgres
    container_name: docker-postgres
    # command: cat EngagedlyData.out | docker exec -i docker-postgres psql -U postgres
    volumes:
      - ./database:/usr/local/var/postgresql@9.6/
    ports:
      - "5432:5432"
    networks:
      - Engagedly


  redis:
    image: 'redis:4.0-alpine'
    networks:
      - Engagedly
  
  super-admin:
    image: super-admin
    command: rails s -p 3001 -b 0.0.0.0
    # command: >
    #   sh -c "resque-pool --environment=development --daemon && rails s - 3001 -b 0.0.0.0 "
     
    environment: 
      SUPER_ADMIN_DATABASE: 'super_admin_development'
      SUPER_ADMIN_USERNAME: 'postgres'
      SUPER_ADMIN_PASSWORD: ''
      SUPER_ADMIN_HOSTNAME: 'db'
    ports:
      - "3001:3001"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local

    depends_on:
      - redis  
      - db
    links:
      - db  
    

  varada:
    image: varada
    # command: >
    #   sh -c "resque-pool --environment=development --daemon && bundle exec rails s -p 3016 -b 0.0.0.0 "
    command: bundle exec rails s -p 3016 -b '0.0.0.0'
    environment: 
      VARADA_DATABASE: 'engagedly_platform_development'
      VARADA_USERNAME: 'postgres'
      VARADA_PASSWORD: ''
      VARADA_HOSTNAME: 'db'
    ports:
      - "3016:3016"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local

    depends_on:
      - redis  
      - db
    links:
      - db  
    

  social-mine:
    image: social-mine
    command: >
      sh -c "resque-pool --environment=development --daemon && rails s -p 3005 -b 0.0.0.0 "
    # command: rails s -p 3005 -P tmp/pids/server_1.pid
    environment: 
      SOCIAL_MINE_DATABASE: 'social_mine_development'
      SOCIAL_MINE_USERNAME: 'postgres'
      SOCIAL_MINE_PASSWORD: ''
      SOCIAL_MINE_HOSTNAME: 'db'
    ports:
      - "3005:3005"
    networks:
      Engagedly:
        aliases:
          - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  
  
  eauth-services:
    image: eauth-services
    command: rails s -p 3015 -b 0.0.0.0 
    # command: >
    #   sh -c "resque-pool --environment=development --daemon && rails s -p 3015 -b 0.0.0.0 "
    environment: 
      EAUTH_SERVICE_DATABASE: 'eauth_service_development'
      EAUTH_SERVICE_USERNAME: 'postgres'
      EAUTH_SERVICE_PASSWORD: ''
      EAUTH_SERVICE_HOSTNAME: 'db'
    ports:
      - "3015:3015"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  

  durjaya:
    image: durjaya
    command: bundle exec rackup --host 0.0.0.0 -p 8000
    ports:
      - "8000:8000"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local

    depends_on:
      - redis  

    
  
  engagedly:
    image: engagedly
    # command: >
    #   sh -c "resque-pool --environment=development --daemon &&  bundle exec rails s -p 3000 -b 0.0.0.0 "
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment: 
      Engagedly_DATABASE: 'engagedly_development'
      Engagedly_USERNAME: 'postgres'
      Engagedly_PASSWORD: ''
      Engagedly_HOSTNAME: 'db'
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db   

    

  advaya:
    image: advaya
    command: padrino s -p 3002 -h 0.0.0.0 
    # command: >
    #   sh -c "resque-pool --environment=development --daemon && padrino s -p 3002 -h 0.0.0.0 "
    environment: 
      ADVAYA_DATABASE: 'advaya_development'
      ADVAYA_USERNAME: 'postgres'
      ADVAYA_PASSWORD: ''
      ADVAYA_HOSTNAME: 'db'
    ports:
      - "3002:3002"
    networks:
       Engagedly:
        aliases:
           - advaya.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  
  
  anmolhrm:
    image: anmolhrm
    command: >
      sh -c "resque-pool --environment=development --daemon && bundle exec rails s -p 3004 -b 0.0.0.0"
    # command: bundle exec rails s -p 3004 -b '0.0.0.0'
    environment: 
      ANMOLHRM_DATABASE: 'anmolhrm_development'
      ANMOLHRM_USERNAME: 'postgres'
      ANMOLHRM_PASSWORD: ''
      ANMOLHRM_HOSTNAME: 'db'
    ports:
      - "3004:3004"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  

  performance-management:
    image: performance-management
    command: >
      sh -c "resque-pool --environment=development --daemon && bundle exec rails s -p 3018 -b 0.0.0.0 "
    # command: bundle exec rails s -p 3018 -b '0.0.0.0'
    environment: 
      PERFORMANCE_MANAGEMENT_DATABASE: 'performance_management_development'
      PERFORMANCE_MANAGEMENT_USERNAME: 'postgres'
      PERFORMANCE_MANAGEMENT_PASSWORD: ''
      PERFORMANCE_MANAGEMENT_HOSTNAME: 'db'
      
    ports:
      - "3018:3018"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local    
    depends_on:
      - redis  
      - db
    links:
      - db  


  ekaksha:
    image: ekaksha
    command: >
      sh -c "resque-pool --environment=development --daemon && bundle exec rails s -p 3019 -b 0.0.0.0 "
    # command: bundle exec rails s -p 3019 -b '0.0.0.0'
    environment: 
      EKAKSHA_DATABASE: 'ekaksha_development'
      EKAKSHA_USERNAME: 'postgres'
      EKAKSHA_PASSWORD: ''
      EKAKSHA_HOSTNAME: 'db'
    ports:
      - "3019:3019"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  


  elastic-interface:
    image: elastic-interface
    command: >
      sh -c "resque-pool --environment=development --daemon && padrino s -p 3014 -h 0.0.0.0 "
    # command: padrino s -p 3014 -h 0.0.0.0 
    environment: 
      ELASTIC_INTERFACE_DATABASE: 'elastic_interface_development'
      ELASTIC_INTERFACE_USERNAME: 'postgres'
      ELASTIC_INTERFACE_PASSWORD: ''
      ELASTIC_INTERFACE_HOSTNAME: 'db'
    ports:
      - "3014:3014"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  
      

  jupiter:
    image: jupiter
    command: >
      sh -c "resque-pool --environment=development --daemon && padrino s -p 3012 -h 0.0.0.0 " 
    # command: padrino s -p 3012 -h 0.0.0.0 
    environment: 
      JUPITER_DATABASE: 'jupiter_development'
      JUPITER_USERNAME: 'postgres'
      JUPITER_PASSWORD: ''
      JUPITER_HOSTNAME: 'db'
    ports:
      - "3012:3012"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  


  pns:
    image: pns
    command: >
      sh -c "resque-pool --environment=development --daemon && padrino s -p 3010 -h 0.0.0.0 "
    # command: padrino s -p 3010 -h 0.0.0.0 
    environment: 
      PNS_DATABASE: 'pns_development'
      PNS_USERNAME: 'postgres'
      PNS_PASSWORD: ''
      PNS_HOSTNAME: 'db'
    ports:
      - "3010:3010"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db    


  enquete:
    image: enquete
    command: >
      sh -c "resque-pool --environment=development --daemon && rails s -p 3007 -b 0.0.0.0 "
    # command: rails s -p 3007 -b 0.0.0.0 
    environment: 
      ENQUETE_DATABASE: 'survey_engagedly_development'
      ENQUETE_USERNAME: 'postgres'
      ENQUETE_PASSWORD: ''
      ENQUETE_HOSTNAME: 'db'
    ports:
      - "3007:3007"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db   

  notification-engine:
    image: notification-engine
    command: >
      sh -c "resque-pool --environment=development --daemon && padrino s -p 3008 -h 0.0.0.0 "
    # command: padrino s -p 3008 -h 0.0.0.0 
    environment: 
      NOTIFIER_DATABASE: 'notifier_development'
      NOTIFIER_USERNAME: 'postgres'
      NOTIFIER_PASSWORD: ''
      NOTIFIER_HOSTNAME: 'db'
    ports:
      - "3008:3008"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  

  phoenix-gamifier:
    image: phoenix-gamifier
    # command: >
    #   sh -c "resque-pool --environment=development --daemon && padrino s -p 3006 -h 0.0.0.0 "
    command: padrino s -p 3006 -h 0.0.0.0 
    environment: 
      PHOENIX_DATABASE: 'phoenix_development' 
      PHOENIX_USERNAME: 'postgres'
      PHOENIX_PASSWORD: ''
      PHOENIX_HOSTNAME: 'db'
    ports:
      - "3006:3006"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  

  learning:
    image: learning
    # command: >
      # sh -c "resque-pool --environment=development --daemon && rails server -p 3009 -b 0.0.0.0 "
    command: rails server -p 3009 -b 0.0.0.0
    environment: 
      LEARNING_DATABASE: 'engagedly_learning'
      LEARNING_USERNAME: 'postgres'
      LEARNING_PASSWORD: ''
      LEARNING_HOSTNAME: 'db'
    ports:
      - "3009:3009"
    networks:
       Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db  

  
  kapalin:
    image: kapalin
    # command: >
      # sh -c "resque-pool --environment=development --daemon && bundle exec rails s -p 3021 -b 0.0.0.0 "
    command: bundle exec rails s -p 3021 -b '0.0.0.0'
    environment: 
      KAPALIN_DATABASE: 'kapalin_development'
      KAPALIN_USERNAME: 'postgres'
      KAPALIN_PASSWORD: ''
      KAPALIN_HOSTNAME: 'db'
    ports:
      - "3021:3021"
    networks:
      Engagedly:
        aliases:
           - app.engagedly.local
    depends_on:
      - redis  
      - db
    links:
      - db   


    
networks:
  Engagedly:
    driver: bridge