# Generated by Django 2.1.5 on 2019-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.TextField(blank=True, null=True)),
                ('description', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('summary', models.TextField()),
            ],
        ),
    ]
